stages:
- stage: Build
  jobs:
  - job: docker_build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:    
    - script: echo build and push to docker!

- stage: Staging
  dependsOn: Build
  jobs:
  - job: Deploy_job1
    displayName: configure
    steps: 
    - script: echo deploying to test1...
  - job: Deploy_job2
    dependsOn: Deploy_job1  
    displayName: Wait for sanity checks
    steps: 
    - script: echo job2...
  - job: Deploy_job3
    displayName: deploy
    dependsOn: Deploy_job2
    pool:
      vmImage: 'Ubuntu 16.04'
    steps: 
    - script: echo job3...
- stage: Prod
  dependsOn: Staging
  jobs:
  - deployment: deploy_to_prod    
    pool:
      vmImage: 'Ubuntu 16.04'
    environment: production    # create environment and/or record deployments
    strategy:                  # runOnce/blue green/rolling/canary, with lifecycle hooks viz, pre/post healthcheck, swap etc
      runOnce:                 # default strategy
        deploy:
          steps:       
          - script: echo deploy to prod environement
